blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'home', to: 'pages#home'
  get 'contact_us', to: 'pages#contact_us'
  resources :articles
  resources :users, except: [:new]
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 200 }
  validates :description, presence: true, length: { minimum: 10}
  validates :user_id, presence: true
  belongs_to :user
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }, format: { with: VALID_EMAIL_REGEX }
  validates :email, presence: true, uniqueness: true
  has_many :articles
  has_secure_password
  before_save { self.email = email.downcase }


end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
   !!current_user
  end
  def require_user
   if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path
   end
  end
  helper_method :current_user, :logged_in?
  # protect_from_forgery unless: -> { request.format.json? }

end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    @article.user = User.first
      if @article.save
       flash[:notice] = "Article was successfully created"
       redirect_to article_path(@article)
      else
       render 'new'
      end
 end

 def show
  # @article = Article.find(params[:id])
 end

 def edit
   # @article = Article.find(params[:id])
 end

 def destroy
  # @article = Article.find(params[:id])
  @article.destroy
  flash[:notice] = "Article was deleted"
  redirect_to articles_path
 end

 def update
  # @article = Article.find(params[:id])
  if @article.update(article_params)
   flash[:notice] = "Article was updated"
   redirect_to article_path(@article)
  else
   flash[:notice] = "Article was not updated"
   render 'edit'
  end
 end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
  def set_article
   @article = Article.find(params[:id])
  end
end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def index
 end

 def about
 end

end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new
  # end
 def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user  && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "You have logged in"
    redirect_to users_path(user)
   else
    flash.now[:danger] = "There was something wrong with your login information"
    render 'new'
   end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
   end
end

blog/app/controllers/user_controller.rb
class UserController < ActionController::Base
  def new
    @user = User.new
  end

  def create
  end
  def update
  end

  private
  def user_params
    params.require(:user).permit(:username, :email)
  end
end

blog/app/controllers/user_token_controller.rb
class UserTokenController < Knock::AuthTokenController
  skip_before_action :verify_authenticity_token
end

blog/app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def new
    @user = User.new
  end
  def index
    @user = User.all
  end

  def create
  @user = User.new(user_params)
  if @user.save
   flash[:success] = "Welcome to the alpha blog #{@user.username}"
   redirect_to articles_path
  else
   render 'new'
  end
 end

 def update
 @user = User.find(params[:id])
 if @user.update(user_params)
  flash[:success] = "Your account was updated successfully"
  redirect_to articles_path
 else
  render 'edit'
 end
end

  def edit
  @user = User.find(params[:id])
 end
 def show
  @user = User.find(params[:id])
 end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/views/articles/_form.html.erb
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
<%= link_to 'Back', articles_path %>
 </div>
</div>

<%= render 'shared/errors', obj: @article %>

blog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<div class="show_break">
<h2>Edit Article</h2>
<p></p>
<%= render 'form' %>

blog/app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div class="show_break">
  <h2>All Articles</h2>
<% @articles.each do |article| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="article-title">
     <%= link_to article.title, article_path(article) %>
    </div>
    <div class="article-body">
     <%= truncate(article.description, length: 100) %>
    </div>

    <div>
      <small class="article-meta-details">Created by: <%= article.user.username %>,
        <%= time_ago_in_words(article.created_at) %> ago,
        last updated: <%= time_ago_in_words(article.updated_at) %> ago
      </small>
    </div>

    <div class="article-actions">
     <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
     <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    </div>
   </div>
  </div>
 </div>
<% end %>
<p></p>
<%= link_to "New Article", new_article_path(@article), class: "btn btn-xs btn-primary" %>

blog/app/views/articles/new.html.erb
<h1>Create an article</h1>
<div class="show_break">
<p>Create New Article</p>
<%= render 'form' %>

blog/app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<div class="show_break">

</div>
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <!-- <h4 class="center"><strong>Description:</strong></h4> -->
 <p></p>
 <hr>
 <%= simple_format(@article.description) %>
 <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> |
 <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %> |
 <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>

blog/app/views/layouts/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" is msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

blog/app/views/layouts/_navigations.html.erb
<%= stylesheet_link_tag "specific_selectors.css" %>
<%= stylesheet_link_tag "css_reset.css" %>

  <header class = "header group" >

    <!-- <img src="app/assets/images/trees666.gif" alt="App Academy Logo" class = "header_nav_logo group"> -->
    <!-- <img src="./assets/eye-animation3.gif" alt="App Academy Logo" class = "header_nav_logo group"> -->
    <nav class = "header_nav group">
      <div class = "bloglogo">
        <%= link_to image_tag("trees666.gif"), root_path %>
      </div>
      <h1 id="Existential Economics" class = "header_nav_name group">Existential Economics</h1>
      <div class="hour_glass_logo">
        <%= image_tag("Hour-Glass.png") %>
      </div>
      <ul class = "header_nav_list group">
        <li><a <%= link_to 'Articles', articles_path %></a></li>
        <li><a <%= link_to 'About', about_path %></a></li>
        <li><a <%= link_to 'Contact Us', contact_us_path %></a></li>

        <!-- <li><a href="#Login">Login</a></li> -->
      </ul>
      <ul class="hamburger-dropdown">
      <li>
      <ul>
        <li><a <%= link_to 'Articles', articles_path %></a></li>
        <li><a <%= link_to 'About', about_path %></a></li>
        <li><a <%= link_to 'Contact Us', contact_us_path %></a></li>




      </ul>
      </li>
    </ul>
    </nav>
  </header>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= render 'layouts/navigations' %>

<html>
  <!-- <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> -->

    <%# <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> %>
    <%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  <!-- </head> -->

  <body>
    <%= yield %>
  </body>
</html>

<% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
<% end %>

blog/app/views/pages/about.html.erb
<h1>About Blog</h1>
<p class="about_copy">Existential Economics was created to be an open platform for anyone to post economic articles. Knowledge is what pushes us forward as a society so feel free to share your opinions, research or research proposals and lets move forward together to a world with open access to education and freedom of information.</p>
<p></p>
<p>*Login functionality will be available shortly so anyone will be able to share their knowledge.</p>

blog/app/views/pages/contact_us.html.erb
<h1>Contact Us</h1>
<div class="show_break">
<p>This page will be up and running shortly, thank you for your patience!</p>

blog/app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>
<div class="show_break">
<h2 class="home_header">Welcome to Existential Economics!</h2>
<p class="home_page">Come learn, share your ideas and help spread information to anyone who is interested.</p>
<div class="home_brain_image">

</div>
<p ></p>
<p class="home_page_copy">We are at a point in time where the disparity between educational opotunity is at an all time high. Teritiary education is unaffordable for the most of human kind and high quality education is reserved for only a tiny percentage of the population. This platform will enable you to share the knowledge you have been privilaged enough to have access to so that anyone will have access to it. If you did research in your masters degree, if you took a course that inspired you or even if you just read a book you found inspiring, share what you learned here so we can all grow together. </p>

<%= link_to 'About', about_path %>

blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

blog/app/views/shared/new.html.erb
<h1>hello</h1>

<%= stylesheet_link_tag "specific_selectors.css" %>
<%= stylesheet_link_tag "css_reset.css" %>

<body class="signup">

  <div class="row">
   <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :username %>
     </div>
     <div class="col-sm-6">
      <%= f.text_field :username, class: "form-control", placeholder: "Your Username", autofocus: true %>
     </div>
    </div>
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :email %>
     </div>
     <div class="col-sm-6">
      <%= f.text_area :email, rows: 1, class: "form-control", placeholder: "Email Adress" %>
     </div>
    </div>
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :password %>
     </div>
     <div class="col-sm-6">
      <%= f.text_area :password_digest, rows: 1, class: "form-control", placeholder: "Your Password" %>
     </div>
    </div>
    <div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
       <%= f.submit "Sign up", class: 'btn btn-primary btn-lg' %>
     </div>
    </div>
  <% end %>
  <%= link_to 'Back', articles_path %>
   </div>
  </div>



  <%= render 'shared/errors', obj: @user %>
</body>

blog/app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Update your account", class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
  </div>
 </div>
</div>

blog/app/views/users/new.html.erb
<%= stylesheet_link_tag "specific_selectors.css" %>
<%= stylesheet_link_tag "css_reset.css" %>

<body class="signup">

  <div class="row">
   <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :username %>
     </div>
     <div class="col-sm-6">
      <%= f.text_field :username, class: "form-control", placeholder: "Your Username", autofocus: true %>
     </div>
    </div>
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :email %>
     </div>
     <div class="col-sm-6">
      <%= f.text_area :email, rows: 1, class: "form-control", placeholder: "Email Adress" %>
     </div>
    </div>
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :password %>
     </div>
     <div class="col-sm-6">
      <%= f.text_area :password_digest, rows: 1, class: "form-control", placeholder: "Your Password" %>
     </div>
    </div>
    <div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
       <%= f.submit "Sign up", class: 'btn btn-primary btn-lg' %>
     </div>
    </div>
  <% end %>
  <%= link_to 'Back', articles_path %>
   </div>
  </div>



  <%= render 'shared/errors', obj: @user %>
</body>